"""What the Quiz screen says about models when a saved quiz exists and another model is selected.

The title of a quiz always names the model that generated THAT quiz (from the backend). Selecting
another model never relabels it; it only adds a hint to use "Regenerate Quiz". The pure helpers of
frontend/app.js are executed with Node against stubbed DOM state.
"""

import json
import shutil
import subprocess
import textwrap
import unittest
from pathlib import Path

APP_JS = Path(__file__).parents[1] / "frontend" / "app.js"
HELPERS = ("quizTypeLabel", "documentQuizTypeBreakdown", "quizPartialSuffix", "quizModelSuffix",
           "quizModelMismatch", "assessmentTitleText")

DRIVER = textwrap.dedent("""
    const fs = require("fs"), vm = require("vm");
    const source = fs.readFileSync(process.argv[1], "utf8");
    function extract(name) {
      const start = source.indexOf(`function ${name}(`);
      if (start < 0) throw new Error(`missing ${name}`);
      let depth = 0, index = source.indexOf("{", start);
      for (let i = index; i < source.length; i++) {
        if (source[i] === "{") depth++;
        if (source[i] === "}" && --depth === 0) return source.slice(start, i + 1);
      }
    }
    const names = JSON.parse(process.argv[2]);
    const code = names.map(extract).join("\\n") + `
      globalThis.quizModelSelect = { value: "", options: [
        { value: "qwen-2.5-7b", text: "Qwen2.5-7B-Instruct" },
        { value: "deepseek-r1-14b", text: "DeepSeek-R1-Distill-Qwen-14B" } ] };
    `;
    const context = vm.createContext({});
    vm.runInContext(code, context);
    const cases = JSON.parse(process.argv[3]);
    const out = cases.map(({ selected, quiz }) => vm.runInContext(
      `quizModelSelect.value = ${JSON.stringify(selected)};
       ({ title: assessmentTitleText(${JSON.stringify(quiz)}), notice: quizModelMismatch(${JSON.stringify(quiz)}) })`, context));
    process.stdout.write(JSON.stringify(out));
""")

QWEN_QUIZ = {
    "title": "Midterm", "difficulty": "easy", "assessment_scope": "document", "document_id": "lecture.pdf",
    "questions": [{"question_type": "single_choice"}] * 12,
    "assessment_plan": {"type_distribution": {"single_choice": 12}},
    "generation_model": {"model_id": "qwen-2.5-7b", "name": "Qwen2.5-7B-Instruct", "quantization": "Q4_K_M"},
}
DEEPSEEK_QUIZ = {**QWEN_QUIZ, "generation_model": {
    "model_id": "deepseek-r1-14b", "name": "DeepSeek-R1-Distill-Qwen-14B", "quantization": "Q4_K_M"}}
OLD_QUIZ = {key: value for key, value in QWEN_QUIZ.items() if key != "generation_model"}


@unittest.skipUnless(shutil.which("node"), "node is not installed")
class QuizModelScreenTests(unittest.TestCase):
    def run_cases(self, cases):
        result = subprocess.run(
            ["node", "-e", DRIVER, str(APP_JS), json.dumps(HELPERS), json.dumps(cases)],
            capture_output=True, text=True, check=True,
        )
        return json.loads(result.stdout)

    def test_a_qwen_quiz_is_never_labelled_deepseek_even_when_deepseek_is_selected(self):
        same, other = self.run_cases([
            {"selected": "qwen-2.5-7b", "quiz": QWEN_QUIZ},
            {"selected": "deepseek-r1-14b", "quiz": QWEN_QUIZ},
        ])
        self.assertIn("Generated by: Qwen2.5-7B-Instruct", same["title"])
        self.assertEqual(same["notice"], "")
        self.assertIn("Generated by: Qwen2.5-7B-Instruct", other["title"])
        self.assertNotIn("Generated by: DeepSeek", other["title"])
        self.assertIn("Selected model differs: press Regenerate Quiz to use it", other["title"])
        self.assertEqual(
            other["notice"],
            "This saved quiz was generated by Qwen2.5-7B-Instruct, not DeepSeek-R1-Distill-Qwen-14B. "
            "Use Regenerate Quiz to create a new one with DeepSeek-R1-Distill-Qwen-14B.",
        )

    def test_a_deepseek_quiz_is_labelled_deepseek_and_the_reverse_hint_appears_for_qwen(self):
        same, other = self.run_cases([
            {"selected": "deepseek-r1-14b", "quiz": DEEPSEEK_QUIZ},
            {"selected": "qwen-2.5-7b", "quiz": DEEPSEEK_QUIZ},
        ])
        self.assertIn("Generated by: DeepSeek-R1-Distill-Qwen-14B", same["title"])
        self.assertEqual(same["notice"], "")
        self.assertIn("Generated by: DeepSeek-R1-Distill-Qwen-14B", other["title"])
        self.assertIn("not Qwen2.5-7B-Instruct", other["notice"])

    def test_a_quiz_without_a_recorded_model_shows_no_model_and_no_hint(self):
        (result,) = self.run_cases([{"selected": "deepseek-r1-14b", "quiz": OLD_QUIZ}])
        self.assertNotIn("Generated by", result["title"])
        self.assertEqual(result["notice"], "")

    def test_the_model_of_a_plan_only_quiz_is_used_when_the_top_level_field_is_missing(self):
        quiz = {**OLD_QUIZ, "assessment_plan": {**QWEN_QUIZ["assessment_plan"], "generation_model": QWEN_QUIZ["generation_model"]}}
        (result,) = self.run_cases([{"selected": "qwen-2.5-7b", "quiz": quiz}])
        self.assertIn("Generated by: Qwen2.5-7B-Instruct", result["title"])


class QuizModelWiringTests(unittest.TestCase):
    def test_the_selector_exists_before_any_create_dialog_and_regenerate_sends_it(self):
        source = APP_JS.read_text(encoding="utf-8")
        landing = source[source.index("function updateQuizLandingLayout()"):]
        landing = landing[:landing.index("\n}\n")]
        self.assertIn("ensureQuizModelSelect();", landing)                       # built with the quiz screen
        dialog = source[source.index("function openQuizCreateDialog()"):]
        self.assertIn("ensureQuizModelSelect();", dialog[:dialog.index("\n}\n")])
        self.assertEqual(source.count("quizModelSelect = document.createElement"), 1)
        regenerate = source[source.index("async function requestQuizRegeneration"):]
        self.assertIn("model_id: request.model_id", regenerate[:regenerate.index("\n}\n")])

    def test_generating_over_a_saved_quiz_says_which_model_it_is(self):
        source = APP_JS.read_text(encoding="utf-8")
        body = source[source.index("async function generateAssessmentQuiz()"):]
        body = body[:body.index("\nasync function regenerateAssessmentQuiz")]
        self.assertIn("quizModelMismatch(currentQuiz)", body)                    # quiz already on screen
        self.assertIn("quizModelMismatch(currentQuiz, generationRequest.model_id)", body)   # served from the API cache


if __name__ == "__main__":
    unittest.main()
